version: '3'

services:
  backend:
    build: ./backend
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: node_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: 10east
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
